.PHONY: clean All

All:
	@echo "----------Building project:[ LaborationFyra - Debug ]----------"
	@cd "LaborationFyra" && "$(MAKE)" -f  "LaborationFyra.mk"
clean:
	@echo "----------Cleaning project:[ LaborationFyra - Debug ]----------"
	@cd "LaborationFyra" && "$(MAKE)" -f  "LaborationFyra.mk" clean
